class Error(object):
    NONE = 0
    INVALID_PACKAGE = 1
    AMBIGUOUS_PACKAGE = 2
    CONFLICTING_PACKAGE = 3
    INVALID_SOURCE = 4
    CONFLICTING_SOURCE = 5
    INVALID_PACKAGE_METADATA = 6
    PACKAGE_BUILD_FAILURE = 7
