#! /usr/bin/env bash
#
# Suppress the SHA commit string in a zkg.meta's template.commit line.

# Get us "modern" regexps with sed.
if [ `uname` == "Linux" ]; then
   sed="sed -r"
else
   sed="sed -E"
fi

$sed -e 's/commit = [0-9a-z]{8}/commit = xxxxxxxx/'
