#! /usr/bin/env bash
#
# Replace timestamps in the zkg log with XXXs. Note, this is different
# from the canonifier used in the Zeek distribution.

# Get us "modern" regexps with sed.
if [ `uname` == "Linux" ]; then
   sed="sed -r"
else
   sed="sed -E"
fi

$sed -e 's/^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}/XXXX-XX-XX XX:XX:XX/'
