#! /usr/bin/env bash

force=""

# This is brittle: any test saying e.g. "zkg -vvv install" instead of "zkg
# install" will no longer have --force. This should either be more robustly
# parsed or set force via an env var or dedicated command line option.

case "$1" in
    install)
        force="--force"
    ;;
    upgrade)
        force="--force"
    ;;
    bundle)
        force="--force"
    ;;
    unbundle)
        force="--force"
    ;;
    remove)
        force="--force"
    ;;
    unload)
        force="--force"
    ;;
    purge)
        force="--force"
    ;;
esac

$TEST_BASE/../zkg --configfile=config "$@" $force
