#! /usr/bin/env python3

# https://pypi.org/project/argcomplete/#global-completion
# PYTHON_ARGCOMPLETE_OK

import logging
import os
import sys

try:
    import git  # noqa: F401
    import semantic_version  # noqa: F401
except ImportError as error:
    print(
        "error: zkg failed to import one or more dependencies:\n"
        "\n"
        "* GitPython:        https://pypi.org/project/GitPython\n"
        "* semantic-version: https://pypi.org/project/semantic-version\n"
        "\n"
        "If you use 'pip', they can be installed like:\n"
        "\n"
        "     pip3 install GitPython semantic-version\n"
        "\n"
        "Also check the following exception output for possible alternate explanations:\n\n"
        f"{type(error).__name__}: {error}",
        file=sys.stderr,
    )
    sys.exit(1)

try:
    # Argcomplete provides command-line completion for users of argparse.
    # We support it if available, but don't complain when it isn't.
    import argcomplete  # noqa: F401
except ImportError:
    pass

# For Zeek-bundled installation, prepend the Python path of the Zeek
# installation. This ensures we find the matching zeekpkg module first,
# avoiding conflicts with installations elsewhere on the system.
ZEEK_PYTHON_DIR: str | None = "@PY_MOD_INSTALL_DIR@"
assert isinstance(ZEEK_PYTHON_DIR, str)
if os.path.isdir(ZEEK_PYTHON_DIR):
    sys.path.insert(0, os.path.abspath(ZEEK_PYTHON_DIR))
else:
    ZEEK_PYTHON_DIR = None

import zeekpkg


def main() -> None:
    parser = zeekpkg.cli.argparser()
    args = parser.parse_args()

    formatter = logging.Formatter(
        "%(asctime)s %(levelname)-8s %(message)s",
        "%Y-%m-%d %H:%M:%S",
    )
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)

    if args.verbose == 1:
        zeekpkg.LOG.setLevel(logging.INFO)
    elif args.verbose >= 2:
        zeekpkg.LOG.setLevel(logging.DEBUG)

    zeekpkg.LOG.addHandler(handler)

    configfile = zeekpkg.CONFIG.find_configfile(args)

    zeekpkg.CONFIG.reset(args)
    zeekpkg.CONFIG.update_from_file(configfile)
    zeekpkg.CONFIG.update_from_args(args)

    manager = zeekpkg.manager.Manager()

    for name, url in zeekpkg.CONFIG.items("sources"):
        if err := manager.add_source(name, url):
            print(
                f'warning: skipped using package source named "{name}" ({url}): {err}',
                file=sys.stderr,
            )

    args.run_cmd(manager, args)


if __name__ == "__main__":
    main()
    sys.exit(0)
