#! /usr/bin/env python3

# https://pypi.org/project/argcomplete/#global-completion
# PYTHON_ARGCOMPLETE_OK

import sys

import zeekpkg


def main() -> None:
    parser = zeekpkg.cli.argparser()
    args = parser.parse_args()

    zeekpkg.logs.configure(args.verbose)

    configfile = zeekpkg.CONFIG.find_configfile(args)

    zeekpkg.CONFIG.reset(args)
    zeekpkg.CONFIG.update_from_file(configfile)
    zeekpkg.CONFIG.update_from_args(args)

    manager = zeekpkg.manager.Manager()

    for name, url in zeekpkg.CONFIG.items("sources"):
        if err := manager.add_source(name, url):
            print(
                f'warning: skipped using package source named "{name}" ({url}): {err}',
                file=sys.stderr,
            )

    args.run_cmd(manager, args)


if __name__ == "__main__":
    main()
    sys.exit(0)
