#! /usr/bin/env python3

# https://pypi.org/project/argcomplete/#global-completion
# PYTHON_ARGCOMPLETE_OK

import logging
import sys

import zeekpkg


def main() -> None:
    parser = zeekpkg.cli.argparser()
    args = parser.parse_args()

    formatter = logging.Formatter(
        "%(asctime)s %(levelname)-8s %(message)s",
        "%Y-%m-%d %H:%M:%S",
    )
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)

    if args.verbose == 1:
        zeekpkg.LOG.setLevel(logging.INFO)
    elif args.verbose >= 2:
        zeekpkg.LOG.setLevel(logging.DEBUG)

    zeekpkg.LOG.addHandler(handler)

    configfile = zeekpkg.CONFIG.find_configfile(args)

    zeekpkg.CONFIG.reset(args)
    zeekpkg.CONFIG.update_from_file(configfile)
    zeekpkg.CONFIG.update_from_args(args)

    manager = zeekpkg.manager.Manager()

    for name, url in zeekpkg.CONFIG.items("sources"):
        if err := manager.add_source(name, url):
            print(
                f'warning: skipped using package source named "{name}" ({url}): {err}',
                file=sys.stderr,
            )

    args.run_cmd(manager, args)


if __name__ == "__main__":
    main()
    sys.exit(0)
