### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
#
# This is loaded when a user activates the plugin. Include scripts here that should be
# loaded automatically at that point.
#



event zeek_init() { print "rot13 script is loaded"; }
